version: "3.8"

services:
    fityoufood-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        networks:
            - app_network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=FitYouFood;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=true;
        depends_on:
            - sqlserver
        image: fityoufood-fityoufood-app
        restart: on-failure

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=YourStrongPassword123!
        ports:
            - "1433:1433"
        networks:
            - app_network
        volumes:
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
    sql_data:

networks:
    app_network:
        driver: bridge
