name: Docker Compose CI/CD

# hi

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build, start and test services
              run: docker compose -f compose.yaml up --build -d

            - name: Wait for Services to Start
              run: |
                  sleep 50
                  docker logs $(docker ps -q -f name=sonarqube)

            - name: Verify Metrics Endpoint
              run: |
                  curl -f http://localhost:8080/metrics || echo "Metrics endpoint not available"

            - name: Generate SonarQube Token
              run: |
                SONAR_TOKEN=$(curl -u admin:admin -X POST "http://localhost:9000/api/user_tokens/generate" -d "name=github-action-token" | jq -r '.token')
                echo "Generated SONAR_TOKEN: ${SONAR_TOKEN}" # Debugging step to check the value
                echo "SONAR_TOKEN=${SONAR_TOKEN}" >> $GITHUB_ENV

            - name: Set SonarQube Scanner environment
              run: |
                echo "sonar.host.url=http://localhost:9000" >> sonar-project.properties
                echo "sonar.login=${{ env.SONAR_TOKEN }}" >> sonar-project.properties

            - name: SonarQube Analysis (.NET)
              run: |
                  docker exec -i $(docker ps -q -f name=fityoufood-app) dotnet sonarscanner begin /k:"your_project_key" /d:sonar.host.url="http://sonarqube:9000" /d:sonar.login="${SONAR_TOKEN}"

                  docker exec -i $(docker ps -q -f name=fityoufood-app) dotnet build ./FitYouFood/FitYouFood.API.csproj

                  docker exec -i $(docker ps -q -f name=fityoufood-app) dotnet-sonarscanner end /d:sonar.login="${SONAR_TOKEN}"

            - name: Tag and Push Docker Image
              run: |
                  docker tag 1ankoz/fityoufood-app:latest ${{ secrets.DOCKER_USERNAME }}/fityoufood-app:latest
                  docker push ${{ secrets.DOCKER_USERNAME }}/fityoufood-app:latest

            - name: Stop and Remove Services
              run: docker compose -f compose.yaml down

            - name: Download Logs from Loggly
              run: |
                curl -H 'Authorization: bearer bc759bfb-b8dc-499c-a924-d6a42f78134a' "https://polibudacicd.loggly.com/apiv2/search?q=*&from=-2h&until=now&size=10" -o loggly_logs.json

                # Optionally, you can output the logs
                cat loggly_logs.json